# Pandas

**Numerical calculation as on matrix and list uses Numpy.**  
**Data analysis, mean, mode, stastical analysis of structured data uses Pandas**

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("police_project.csv")

In [3]:
df.columns

Index(['stop_date', 'stop_time', 'county_name', 'driver_gender',
       'driver_age_raw', 'driver_age', 'driver_race', 'violation_raw',
       'violation', 'search_conducted', 'search_type', 'stop_outcome',
       'is_arrested', 'stop_duration', 'drugs_related_stop'],
      dtype='object')

In [4]:
df.head()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91741 entries, 0 to 91740
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           91741 non-null  object
 1   stop_time           91741 non-null  object
 2   county_name         0 non-null      float64
 3   driver_gender       86406 non-null  object
 4   driver_age_raw      86414 non-null  float64
 5   driver_age          86120 non-null  float64
 6   driver_race         86408 non-null  object
 7   violation_raw       86408 non-null  object
 8   violation           86408 non-null  object
 9   search_conducted    91741 non-null  bool
 10  search_type         3196 non-null   object
 11  stop_outcome        86408 non-null  object
 12  is_arrested         86408 non-null  object
 13  stop_duration       86408 non-null  object
 14  drugs_related_stop  91741 non-null  bool
dtypes: bool(2), float64(3), object(10)
memory usage: 9.3+ MB

In [6]:
df.head()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [7]:
df.describe()

       county_name  driver_age_raw    driver_age
count          0.0    86414.000000  86120.000000
mean           NaN     1970.491228     34.011333
std            NaN      110.914909     12.738564
min            NaN        0.000000     15.000000
25%            NaN     1967.000000     23.000000
50%            NaN     1980.000000     31.000000
75%            NaN     1987.000000     43.000000
max            NaN     8801.000000     99.000000

In [8]:
df["driver_gender"]

0        M
1        M
2        M
3        M
4        F
        ..
91736    M
91737    F
91738    M
91739    M
91740    M
Name: driver_gender, Length: 91741, dtype: object

In [9]:
df.isnull().sum()

stop_date                 0
stop_time                 0
county_name           91741
driver_gender          5335
driver_age_raw         5327
driver_age             5621
driver_race            5333
violation_raw          5333
violation              5333
search_conducted          0
search_type           88545
stop_outcome           5333
is_arrested            5333
stop_duration          5333
drugs_related_stop        0
dtype: int64

In [10]:
df.shape

(91741, 15)

In [11]:
df.isna().mean()

stop_date             0.000000
stop_time             0.000000
county_name           1.000000
driver_gender         0.058153
driver_age_raw        0.058066
driver_age            0.061270
driver_race           0.058131
violation_raw         0.058131
violation             0.058131
search_conducted      0.000000
search_type           0.965163
stop_outcome          0.058131
is_arrested           0.058131
stop_duration         0.058131
drugs_related_stop    0.000000
dtype: float64

In [12]:
df["driver_age"].mean()

34.011333023687875

In [13]:
df.head(2)

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [14]:
df.drop(['driver_age_raw','violation_raw'],axis=1, inplace=True)

In [15]:
df.head()

,stop_date,stop_time,county_name,driver_gender,driver_age,driver_race,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,20.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,40.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,33.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,19.0,White,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,21.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False

In [16]:
df.isnull().sum()

stop_date                 0
stop_time                 0
county_name           91741
driver_gender          5335
driver_age             5621
driver_race            5333
violation              5333
search_conducted          0
search_type           88545
stop_outcome           5333
is_arrested            5333
stop_duration          5333
drugs_related_stop        0
dtype: int64

In [17]:
df.head(10)

,stop_date,stop_time,county_name,driver_gender,driver_age,driver_race,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,20.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,40.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,33.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,19.0,White,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,21.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
5,2005-03-23,09:45,NaN,M,23.0,Black,Equipment,False,NaN,Citation,False,0-15 Min,False
6,2005-04-01,17:30,NaN,M,36.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
7,2005-06-06,13:20,NaN,F,19.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
8,2005-07-13,10:15,NaN,M,35.0,Black,Speeding,False,NaN,Citation,False,0-15 Min,False
9,2005-07-13,15:45,NaN,M,35.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False

In [18]:
df.shape

(91741, 13)

In [19]:
df.dtypes

stop_date              object
stop_time              object
county_name           float64
driver_gender          object
driver_age            float64
driver_race            object
violation              object
search_conducted         bool
search_type            object
stop_outcome           object
is_arrested            object
stop_duration          object
drugs_related_stop       bool
dtype: object

In [20]:
df.fillna(df.mean(numeric_only=True))

,stop_date,stop_time,county_name,driver_gender,driver_age,driver_race,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,20.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,40.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,33.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,19.0,White,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,21.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31,20:27,NaN,M,29.0,White,Speeding,False,NaN,Warning,False,0-15 Min,False
91737,2015-12-31,20:35,NaN,F,33.0,White,Equipment,False,NaN,Warning,False,0-15 Min,False
91738,2015-12-31,20:45,NaN,M,23.0,White,Moving violation,False,NaN,Warning,False,0-15 Min,False
91739,2015-12-31,21:42,NaN,M,22.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
91740,2015-12-31,22:46,NaN,M,56.0,Hispanic,Speeding,False,NaN,Citation,False,0-15 Min,False

In [21]:
df.isnull().sum()

stop_date                 0
stop_time                 0
county_name           91741
driver_gender          5335
driver_age             5621
driver_race            5333
violation              5333
search_conducted          0
search_type           88545
stop_outcome           5333
is_arrested            5333
stop_duration          5333
drugs_related_stop        0
dtype: int64

In [22]:
df.head()

,stop_date,stop_time,county_name,driver_gender,driver_age,driver_race,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,20.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,40.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,33.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,19.0,White,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,21.0,White,Speeding,False,NaN,Citation,False,0-15 Min,False

In [23]:
df.isnull().sum()

stop_date                 0
stop_time                 0
county_name           91741
driver_gender          5335
driver_age             5621
driver_race            5333
violation              5333
search_conducted          0
search_type           88545
stop_outcome           5333
is_arrested            5333
stop_duration          5333
drugs_related_stop        0
dtype: int64

In [24]:
df.drop("county_name",axis=1,inplace=True)

In [25]:
df.dropna(inplace=True)

In [26]:
df.isnull().sum()

stop_date             0
stop_time             0
driver_gender         0
driver_age            0
driver_race           0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
dtype: int64

In [27]:
df['date_time'] = df['stop_date'] + ' ' + df['stop_time']

In [28]:
df.shape

(3193, 13)

In [29]:
df.dtypes

stop_date              object
stop_time              object
driver_gender          object
driver_age            float64
driver_race            object
violation              object
search_conducted         bool
search_type            object
stop_outcome           object
is_arrested            object
stop_duration          object
drugs_related_stop       bool
date_time              object
dtype: object

In [30]:
df.head()

,stop_date,stop_time,driver_gender,driver_age,driver_race,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,date_time
24,2005-08-28,01:00,M,26.0,White,Moving violation,True,"Incident to Arrest,Protective Frisk",Arrest Driver,True,16-30 Min,False,2005-08-28 01:00
40,2005-10-01,00:00,M,17.0,White,Equipment,True,Probable Cause,Arrest Driver,True,16-30 Min,True,2005-10-01 00:00
41,2005-10-01,00:00,M,17.0,White,Equipment,True,Probable Cause,Citation,False,30+ Min,True,2005-10-01 00:00
80,2005-10-02,09:30,M,30.0,White,Speeding,True,Incident to Arrest,Arrest Driver,True,30+ Min,False,2005-10-02 09:30
106,2005-10-03,14:00,M,27.0,Black,Equipment,True,Probable Cause,Citation,False,16-30 Min,False,2005-10-03 14:00

In [31]:
df.set_index('date_time',inplace=True)

In [32]:
df['stop_date'] = df['stop_date'].str.replace('-','/')

In [33]:
df.head()

,stop_date,stop_time,driver_gender,driver_age,driver_race,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
date_time,,,,,,,,,,,,
2005-08-28 01:00,2005/08/28,01:00,M,26.0,White,Moving violation,True,"Incident to Arrest,Protective Frisk",Arrest Driver,True,16-30 Min,False
2005-10-01 00:00,2005/10/01,00:00,M,17.0,White,Equipment,True,Probable Cause,Arrest Driver,True,16-30 Min,True
2005-10-01 00:00,2005/10/01,00:00,M,17.0,White,Equipment,True,Probable Cause,Citation,False,30+ Min,True
2005-10-02 09:30,2005/10/02,09:30,M,30.0,White,Speeding,True,Incident to Arrest,Arrest Driver,True,30+ Min,False
2005-10-03 14:00,2005/10/03,14:00,M,27.0,Black,Equipment,True,Probable Cause,Citation,False,16-30 Min,False

In [34]:
class Animal:
    def speak(self):
        print("voice")
class cat:
    def speak(Animal):
        print("Meo meo")
class wolf:
    def speak(self):
        print("ao ao")

my_object = [Animal(),cat(),wolf()]
for obj in my_object:
    obj.speak()

voice
Meo meo
ao ao

In [35]:
cat1 = cat()
cat1.speak()

Meo meo

## over write

In [36]:
from abc import ABC, abstractmethod

In [38]:
class Animal:
    @abstractmethod
    def speak(ABC):
        print("voice")
class cat:
    def speak(Animal):
        print("Meo meo")
class wolf:
    def speak(self):
        print("ao ao")
def voice(animal: Animal):
    animal.speak()

c1 = cat()
w1 = wolf()
voice(w1)

ao ao

In [1]:
class Animal():
    def __init__(self,color,teeth):
        self.__color=color
        self.__teeth=teeth
    def speak(Animal):
        print(f"{self.color} with the {self.teeth})
class cat(Animal):
    def speak(self):
        print(f"{self.teeth} with the {self.color})

c1 = cat("white",24)
c1.speak()

SyntaxError: unterminated string literal (detected at line 6) (2444596171.py, line 6)

In [ ]:
# broadcasting
# functions
# encapsulation
# classes
# polymorphism
# Abstraction