In [3]:
import pandas as pd

In [5]:
df_test = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [3, 4, 5]
})
print(df_test)

   A  B
0  1  3
1  2  4
2  3  5

In [6]:
df = pd.read_csv('../../data/police_project.csv')
df.head()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [7]:
df.dtypes

stop_date              object
stop_time              object
county_name           float64
driver_gender          object
driver_age_raw        float64
driver_age            float64
driver_race            object
violation_raw          object
violation              object
search_conducted         bool
search_type            object
stop_outcome           object
is_arrested            object
stop_duration          object
drugs_related_stop       bool
dtype: object

In [8]:
df.isnull()

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False
91737,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False
91738,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False
91739,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False
91740,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False

In [9]:
df.isnull().sum()

stop_date                 0
stop_time                 0
county_name           91741
driver_gender          5335
driver_age_raw         5327
driver_age             5621
driver_race            5333
violation_raw          5333
violation              5333
search_conducted          0
search_type           88545
stop_outcome           5333
is_arrested            5333
stop_duration          5333
drugs_related_stop        0
dtype: int64

In [17]:
df['county_name'].head(20)

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
Name: county_name, dtype: float64

In [18]:
df.shape

(91741, 15)

In [20]:
df.drop('county_name', axis=1, inplace=True)

In [21]:
df.head()

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [22]:
df.isnull().sum()

stop_date                 0
stop_time                 0
driver_gender          5335
driver_age_raw         5327
driver_age             5621
driver_race            5333
violation_raw          5333
violation              5333
search_conducted          0
search_type           88545
stop_outcome           5333
is_arrested            5333
stop_duration          5333
drugs_related_stop        0
dtype: int64

In [23]:
df['search_type'].value_counts()

search_type
Incident to Arrest                                          1219
Probable Cause                                               891
Inventory                                                    220
Reasonable Suspicion                                         197
Protective Frisk                                             161
Incident to Arrest,Inventory                                 129
Incident to Arrest,Probable Cause                            106
Probable Cause,Reasonable Suspicion                           75
Incident to Arrest,Inventory,Probable Cause                   34
Incident to Arrest,Protective Frisk                           33
Probable Cause,Protective Frisk                               33
Inventory,Probable Cause                                      22
Incident to Arrest,Reasonable Suspicion                       13
Inventory,Protective Frisk                                    11
Incident to Arrest,Inventory,Protective Frisk                 11
Protective Frisk,Reasonable Suspicion                         11
Incident to Arrest,Probable Cause,Protective Frisk            10
Incident to Arrest,Probable Cause,Reasonable Suspicion         6
Incident to Arrest,Inventory,Reasonable Suspicion              4
Inventory,Reasonable Suspicion                                 4
Inventory,Probable Cause,Protective Frisk                      2
Inventory,Probable Cause,Reasonable Suspicion                  2
Incident to Arrest,Protective Frisk,Reasonable Suspicion       1
Probable Cause,Protective Frisk,Reasonable Suspicion           1
Name: count, dtype: int64

In [24]:
df['search_type'] = df['search_type'].fillna('Unknown')

In [25]:
df.isnull().sum()

stop_date                0
stop_time                0
driver_gender         5335
driver_age_raw        5327
driver_age            5621
driver_race           5333
violation_raw         5333
violation             5333
search_conducted         0
search_type              0
stop_outcome          5333
is_arrested           5333
stop_duration         5333
drugs_related_stop       0
dtype: int64

In [26]:
df.dropna(inplace=True)

In [27]:
df.isnull().sum()

stop_date             0
stop_time             0
driver_gender         0
driver_age_raw        0
driver_age            0
driver_race           0
violation_raw         0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
dtype: int64

In [28]:
df.shape

(86113, 14)

In [30]:
comb = df.stop_date.str.cat(df.stop_time, sep = ' ')

In [31]:
df['date_time'] = pd.to_datetime(comb)

In [32]:
df.head()

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,date_time
0,2005-01-02,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,Unknown,Citation,False,0-15 Min,False,2005-01-02 01:55:00
1,2005-01-18,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,Unknown,Citation,False,0-15 Min,False,2005-01-18 08:15:00
2,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,Unknown,Citation,False,0-15 Min,False,2005-01-23 23:15:00
3,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,Unknown,Arrest Driver,True,16-30 Min,False,2005-02-20 17:15:00
4,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,Unknown,Citation,False,0-15 Min,False,2005-03-14 10:00:00

In [33]:
df.set_index('date_time', inplace=True)

In [34]:
df.head()

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
date_time,,,,,,,,,,,,,,
2005-01-02 01:55:00,2005-01-02,01:55,M,1985.0,20.0,White,Speeding,Speeding,False,Unknown,Citation,False,0-15 Min,False
2005-01-18 08:15:00,2005-01-18,08:15,M,1965.0,40.0,White,Speeding,Speeding,False,Unknown,Citation,False,0-15 Min,False
2005-01-23 23:15:00,2005-01-23,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,Unknown,Citation,False,0-15 Min,False
2005-02-20 17:15:00,2005-02-20,17:15,M,1986.0,19.0,White,Call for Service,Other,False,Unknown,Arrest Driver,True,16-30 Min,False
2005-03-14 10:00:00,2005-03-14,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,Unknown,Citation,False,0-15 Min,False

In [36]:
df.drop(["stop_date","stop_time"],axis=1, inplace=True)

In [37]:
df.head()

,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
date_time,,,,,,,,,,,,
2005-01-02 01:55:00,M,1985.0,20.0,White,Speeding,Speeding,False,Unknown,Citation,False,0-15 Min,False
2005-01-18 08:15:00,M,1965.0,40.0,White,Speeding,Speeding,False,Unknown,Citation,False,0-15 Min,False
2005-01-23 23:15:00,M,1972.0,33.0,White,Speeding,Speeding,False,Unknown,Citation,False,0-15 Min,False
2005-02-20 17:15:00,M,1986.0,19.0,White,Call for Service,Other,False,Unknown,Arrest Driver,True,16-30 Min,False
2005-03-14 10:00:00,F,1984.0,21.0,White,Speeding,Speeding,False,Unknown,Citation,False,0-15 Min,False